### PR TITLE
feat: don't use static binaries in initrd

### PR DESCRIPTION
**Pull request by DavHau**
Fix some bugs and stop using static packages for initrd.
This reduces the size of the tarball.

### CODE REVIEW

**Comment by phaer** [comment]
Thanks! As discussed, I'd prefer to keep just the binaries for things like unshare, ip, parted, etc. Not the complete packages.

**Comment by DavHau** [comment]
I'm not sure what's a good way to strip down the binaries of a dynamically linked package.
I could add a postInstall hook that deletes some of the unneeded binaries, but this in turn will trigger a cache miss and a re-build.

Alternatively we could build these binaries statically, but this will likely cost more space than it can save, due to duplication through the static linking.

**Comment by phaer** [comment]
Not sure I understand you correctly here, we could also quickly discuss this in our call later today :)

In my understanding, most affected binaries - all except static nix, and ip & kexec for the host  - were already linked dynamically. You can just keep the bins in extraBins and make-initrd automagically ensures that required libraries are included in the final closure :)

**Comment by DavHau** [comment]
Oops, my brain read nixStatic and made assumptions... I reverted everything to go back to `extraBin` and only changed `nixStatic` to `nix`.

**Comment by phaer** [comment]
Thanks!

**Pull request merged**
